//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.09 at 02:21:55 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cgd.pt/schemas/countries/country-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.cgd.schemas.countries.country_web_service;
